#!/bin/bash
set -e

echo AAAAAAAAAAAAAAAAAAAA
function getDockerSocketGroup () {
	echo "$(ls -al /var/run/docker.sock | awk '{print $4}')"
}
echo AAAAAwwwwwwwwwwwwwwAAAAAA

# # Run every files in /etc/entrypoint.d
# for _file in $(find /etc/entrypoint.d -type f -iname *.sh | sort); do
#     sudo chmod +x ${_file}
#     sudo sh ${_file}
# done
echo BBBBBBBBBBBBBBBBBBB


# Change docker socket user
echo ''
echo "***** docker-socket *****"
echo "Current user: $(whoami)"
echo "/var/run/docker.sock is currently in group:" $(getDockerSocketGroup)
echo "Changing group of docker.sock to: $DOCKER_GROUP"
sudo chown :$DOCKER_GROUP /var/run/docker.sock
echo "/var/run/docker.sock is now in group:" $(getDockerSocketGroup)
echo "*************************"
echo ''
echo CCCCCCCCCCCCCCCCCCCCCCCC

# Running command
exec /sbin/tini -- "$@"






# echo "==> Launching the Docker daemon..."
# dind dockerd --storage-driver=overlay $DOCKER_EXTRA_OPTS &

# while(! docker info > /dev/null 2>&1); do
#     echo "==> Waiting for the Docker daemon to come online..."
#     sleep 1
# done
# echo "==> Docker Daemon is up and running!"

# # Execute command
# exec "$@"
