FROM docker/compose:alpine-1.25.4 as compose

FROM docker:{{DIND_VERSION}}-dind

LABEL maintainer="Hexosse <hexosse@gmail.com>" \
    org.opencontainers.image.title="docker-suite dsuite/jenkins_dind_agent:{{DIND_VERSION}} image" \
    org.opencontainers.image.description="Jenkins docker in docker agent for dsuite/jenkins" \
    org.opencontainers.image.authors="Hexosse <hexosse@gmail.com>" \
    org.opencontainers.image.vendor="docker-suite" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.url="https://github.com/docker-suite/jenkins_dind_agent" \
    org.opencontainers.image.source="https://github.com/docker-suite/jenkins_dind_agent" \
    org.opencontainers.image.documentation="https://github.com/docker-suite/jenkins_dind_agent/blob/master/Readme.md" \
    org.opencontainers.image.created="{{DOCKER_IMAGE_CREATED}}" \
    org.opencontainers.image.revision="{{DOCKER_IMAGE_REVISION}}"

# Github token
ARG GH_TOKEN


## Install alpine-base
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk update \
    # Download the install-base script and run it
    && apk add curl \
    && curl -s -o /tmp/install-base.sh https://raw.githubusercontent.com/docker-suite/Install-Scripts/master/alpine-base/install-base.sh \
    && sh /tmp/install-base.sh \
    && rm -f /entrypoint.sh \
	# Clear apk's cache
	&& apk-cleanup


## Install packages
RUN \
	# Print executed commands
	set -x \
    # Update repository indexes
    && apk update \
    # Add tools commonly used
    && apk-install --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/  --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ \
        bash \
        bzip2 \
        ca-certificates \
        docker-bash-completion \
        g++ \
        gcc \
        git \
        make \
        openjdk8 \
        openssh-client \
        make \
        sudo \
        tar \
        unzip \
        zip \
        wget \
        nss \
	# Clear apk's cache
	&& apk-cleanup


## Install docker-compose
COPY --from=compose /usr/local/bin/docker-compose /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

## Entrypoint
ENTRYPOINT ["dockerd-entrypoint.sh"]
CMD []
